// Code generated by hertz generator.

package main

import (
	"context"
	"gitee.com/ywengineer/smart-kit/pkg/apps"
	"gorm.io/gorm"
)

func main() {
	if h := apps.NewHertzApp("smart-payment",
		apps.NewDefaultContext,
		func(ctx apps.SmartContext) {
			sqlRunner(ctx.Rdb())
		},
		func(ctx context.Context) {
			// ignore
		},
	); h != nil {
		register(h)
		h.Spin()
	}
}

func sqlRunner(db *gorm.DB) {
	//hlog.Info(db.ToSQL(func(tx *gorm.DB) *gorm.DB {
	//	return tx.WithContext(context.Background()).Clauses(clause.OnConflict{
	//		Columns:   []clause.Column{{Name: "passport"}},                            // 冲突字段（唯一索引）
	//		DoUpdates: clause.AssignmentColumns([]string{"updated_at", "deleted_at"}), // 更新字段
	//	}).Create(&model2.WhiteList{Passport: 100})
	//}))
}
