// Code generated by hertz generator.

package purchase

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyMw() []app.HandlerFunc {
	// your code...
	return nil
}
