// Code generated by hertz generator.

package passport

import (
	"gitee.com/ywengineer/smart-kit/passport/internal"
	"gitee.com/ywengineer/smart-kit/passport/internal/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bindMw() []app.HandlerFunc {
	return middleware.JwtWithValidate(middleware.IsUserMatch(internal.UserTypePlayer))
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	return nil
}
