// Code generated by hertz generator.

package pst

import (
	"gitee.com/ywengineer/smart-kit/passport/internal"
	"gitee.com/ywengineer/smart-kit/passport/internal/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mgrMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passportMw() []app.HandlerFunc {
	return middleware.JwtWithValidate(middleware.IsUserMatch(internal.UserTypeMgr))
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pageMw() []app.HandlerFunc {
	// your code...
	return nil
}
