// Code generated by hertz generator.

package mgr

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	mgr "github.com/ywengineer/smart-kit/passport/biz/model/mgr"
)

// Sign .
// @router /mgr/sign [POST]
func Sign(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mgr.MgrUser
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(string)

	c.JSON(consts.StatusOK, resp)
}
