// Code generated by hertz generator.

package mgr

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Add .
// @router /mgr/white-list/add [GET]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req int64
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(bool)

	c.JSON(consts.StatusOK, resp)
}

// Remove .
// @router /mgr/white-list/rm [GET]
func Remove(ctx context.Context, c *app.RequestContext) {
	var err error
	var req int64
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(bool)

	c.JSON(consts.StatusOK, resp)
}
