// Code generated by hertz generator.

package handler

import (
	"context"
	"fmt"
	"gitee.com/ywengineer/smart-kit/payment/internal/queue"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}

// TestQueue .
func TestQueue(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, utils.H{
		"message": fmt.Sprintf("test queue message published: %+v", queue.PublishTest(false)),
	})
}

// TestFailQueue .
func TestFailQueue(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, utils.H{
		"message": fmt.Sprintf("test queue message published: %+v", queue.PublishTest(true)),
	})
}
