// Code generated by hertz generator.

package openapi

import (
	"context"
	"errors"

	openapi "gitee.com/ywengineer/smart-kit/payment/biz/model/openapi"
	"gitee.com/ywengineer/smart-kit/payment/pkg/model"
	"gitee.com/ywengineer/smart-kit/pkg/apps"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"gorm.io/gorm"
)

// Compare .
// @router /api/compare [POST]
func Compare(ctx context.Context, c *app.RequestContext) {
	var err error
	var req openapi.CompareReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	//
	sc := apps.GetContext(ctx)
	var lost []string
	m := &model.Purchase{}
	// 遍历 req.Invoices，判断是否存在
	for _, invoice := range req.Invoices {
		if err = sc.Rdb().
			WithContext(ctx).
			First(m, "transaction_id = ?", invoice).
			Error; errors.Is(err, gorm.ErrRecordNotFound) {
			lost = append(lost, invoice)
		}
	}
	resp := new(openapi.CompareResp)
	resp.Invoices = lost
	c.JSON(consts.StatusOK, resp)
}
