// Code generated by hertz generator.

package openapi

import (
	"context"

	openapi "gitee.com/ywengineer/smart-kit/payment/biz/model/openapi"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Health .
// @router /health [GET]
func Health(ctx context.Context, c *app.RequestContext) {
	var _ error

	resp := new(openapi.HealthResp)

	c.JSON(consts.StatusOK, resp)
}
