// Code generated by hertz generator.

package passport

import (
	"context"
	"github.com/ywengineer/smart-kit/passport/pkg"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	passport "github.com/ywengineer/smart-kit/passport/biz/model/passport"
)

// Bind .
// @router /bind [GET]
func Bind(ctx context.Context, c *app.RequestContext) {
	var err error
	var req passport.BindReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, validateErr(err))
		return
	}
	// ano
	switch req.Type {
	case passport.AccountType_EMail, passport.AccountType_Mobile:
		c.JSON(consts.StatusNotImplemented, ErrTodo)
		return
	default:
	}
	//
	_ = ctx.Value(pkg.ContextKeySmart).(pkg.SmartContext)
	//
	resp := new(passport.LoginResp)

	c.JSON(consts.StatusOK, resp)
}
