// Code generated by hertz generator.

package passport

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	passport "github.com/ywengineer/smart-kit/passport/biz/model/passport"
)

// Register .
// @router /register [GET]
func Register(ctx context.Context, c *app.RequestContext) {
	var req passport.RegisterReq
	err := c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	// exists type and id?

	resp := new(passport.LoginResp)

	c.JSON(consts.StatusOK, resp)
}
