// Code generated by hertz generator.

package purchase

import (
	"context"

	common "gitee.com/ywengineer/smart-kit/payment/biz/model/common"
	purchase "gitee.com/ywengineer/smart-kit/payment/biz/model/purchase"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Verify .
// @router /verify [POST]
func Verify(ctx context.Context, c *app.RequestContext) {
	var err error
	var req purchase.VerifyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.ApiResult)

	c.JSON(consts.StatusOK, resp)
}
