// Code generated by hertz generator.

package mgr

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/ywengineer/smart-kit/passport/internal/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mgrMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _white_listMw() []app.HandlerFunc {
	return middleware.Jwt()
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pageMw() []app.HandlerFunc {
	// your code...
	return nil
}
