// Code generated by hertz generator.

package simulate

import (
	"context"

	common "gitee.com/ywengineer/smart-kit/payment/biz/model/common"
	simulate "gitee.com/ywengineer/smart-kit/payment/biz/model/simulate"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Simulate .
// @router /simulate [GET]
func Simulate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req simulate.SimulateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.ApiResult)

	c.JSON(consts.StatusOK, resp)
}
