// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	common "gitee.com/ywengineer/smart-kit/payment/biz/router/common"
	openapi "gitee.com/ywengineer/smart-kit/payment/biz/router/openapi"
	purchase "gitee.com/ywengineer/smart-kit/payment/biz/router/purchase"
	simulate "gitee.com/ywengineer/smart-kit/payment/biz/router/simulate"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	purchase.Register(r)

	simulate.Register(r)

	common.Register(r)

	openapi.Register(r)
}
