// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	openapi "gitee.com/ywengineer/smart-kit/payment/biz/router/openapi"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	openapi.Register(r)
}
