// Code generated by hertz generator.

package main

import (
	"context"
	model2 "gitee.com/ywengineer/smart-kit/passport/internal/model"
	"gitee.com/ywengineer/smart-kit/pkg/apps"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func main() {
	if h := apps.NewHertzApp("smart-passport",
		apps.NewDefaultContext,
		func(ctx apps.SmartContext) {
			sqlRunner(ctx.Rdb())
		},
		func(ctx context.Context) {
			// ignore
		},
		apps.WithModels(
			&model2.Passport{},
			&model2.PassportPunish{},
			&model2.PassportBinding{},
			&model2.WhiteList{},
			&model2.MgrUser{},
		),
	); h != nil {
		register(h)
		h.Spin()
	}
}

func sqlRunner(db *gorm.DB) {
	hlog.Info(db.ToSQL(func(tx *gorm.DB) *gorm.DB {
		return tx.WithContext(context.Background()).Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "passport"}},                            // 冲突字段（唯一索引）
			DoUpdates: clause.AssignmentColumns([]string{"updated_at", "deleted_at"}), // 更新字段
		}).Create(&model2.WhiteList{Passport: 100})
	}))
}
