// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/Pay.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付订单验证地址: 充值服地址/rc/verify, 返回ApiResult
type PayReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *string                `protobuf:"bytes,1,req,name=receipt" json:"receipt,omitempty"`         // 订单数据
	GameId        *string                `protobuf:"bytes,2,req,name=gameId" json:"gameId,omitempty"`           // 游戏ID
	ServerId      *string                `protobuf:"bytes,3,req,name=serverId" json:"serverId,omitempty"`       // 服务器ID
	Passport      *string                `protobuf:"bytes,4,req,name=passport" json:"passport,omitempty"`       // 账号ID
	PlayerId      *string                `protobuf:"bytes,5,req,name=playerId" json:"playerId,omitempty"`       // 玩家ID
	PlayerName    *string                `protobuf:"bytes,6,req,name=playerName" json:"playerName,omitempty"`   // 玩家名称
	Channel       *string                `protobuf:"bytes,7,req,name=channel" json:"channel,omitempty"`         // 支付渠道. google, apple
	Signature     *string                `protobuf:"bytes,8,opt,name=signature" json:"signature,omitempty"`     // Google订单检验签名数据
	Locale        *string                `protobuf:"bytes,9,opt,name=locale" json:"locale,omitempty"`           // 区域码（当前设置的区域）
	CreateTime    *int64                 `protobuf:"varint,10,opt,name=createTime" json:"createTime,omitempty"` // 账号注册时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayReceipt) Reset() {
	*x = PayReceipt{}
	mi := &file_pkg_proto_Pay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReceipt) ProtoMessage() {}

func (x *PayReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Pay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReceipt.ProtoReflect.Descriptor instead.
func (*PayReceipt) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Pay_proto_rawDescGZIP(), []int{0}
}

func (x *PayReceipt) GetReceipt() string {
	if x != nil && x.Receipt != nil {
		return *x.Receipt
	}
	return ""
}

func (x *PayReceipt) GetGameId() string {
	if x != nil && x.GameId != nil {
		return *x.GameId
	}
	return ""
}

func (x *PayReceipt) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *PayReceipt) GetPassport() string {
	if x != nil && x.Passport != nil {
		return *x.Passport
	}
	return ""
}

func (x *PayReceipt) GetPlayerId() string {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return ""
}

func (x *PayReceipt) GetPlayerName() string {
	if x != nil && x.PlayerName != nil {
		return *x.PlayerName
	}
	return ""
}

func (x *PayReceipt) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

func (x *PayReceipt) GetSignature() string {
	if x != nil && x.Signature != nil {
		return *x.Signature
	}
	return ""
}

func (x *PayReceipt) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *PayReceipt) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

// 查询订阅地址: 充值服地址/rc/subs, 返回 QuerySubs.Ret
type QuerySubs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        *string                `protobuf:"bytes,1,req,name=gameId" json:"gameId,omitempty"`     // 游戏ID
	ServerId      *string                `protobuf:"bytes,2,req,name=serverId" json:"serverId,omitempty"` // 服务器ID
	PlayerId      *string                `protobuf:"bytes,3,req,name=playerId" json:"playerId,omitempty"` // 玩家ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySubs) Reset() {
	*x = QuerySubs{}
	mi := &file_pkg_proto_Pay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySubs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySubs) ProtoMessage() {}

func (x *QuerySubs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Pay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySubs.ProtoReflect.Descriptor instead.
func (*QuerySubs) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Pay_proto_rawDescGZIP(), []int{1}
}

func (x *QuerySubs) GetGameId() string {
	if x != nil && x.GameId != nil {
		return *x.GameId
	}
	return ""
}

func (x *QuerySubs) GetServerId() string {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return ""
}

func (x *QuerySubs) GetPlayerId() string {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return ""
}

// code取值如下:
// c01, // 正常处理成功
// c02, // 服务器异常
// c03, // 处理失败(错误消息)
type ApiResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *string                `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`            //
	Msg           *string                `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`              //
	ErrorCode     *int32                 `protobuf:"varint,3,opt,name=errorCode" json:"errorCode,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResult) Reset() {
	*x = ApiResult{}
	mi := &file_pkg_proto_Pay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResult) ProtoMessage() {}

func (x *ApiResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Pay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResult.ProtoReflect.Descriptor instead.
func (*ApiResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Pay_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResult) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *ApiResult) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

func (x *ApiResult) GetErrorCode() int32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

type QuerySubs_Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *string                `protobuf:"bytes,1,req,name=productId" json:"productId,omitempty"`  // 产品ID
	LeftMills     *int64                 `protobuf:"varint,2,req,name=leftMills" json:"leftMills,omitempty"` // 剩余时间(毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySubs_Subscription) Reset() {
	*x = QuerySubs_Subscription{}
	mi := &file_pkg_proto_Pay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySubs_Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySubs_Subscription) ProtoMessage() {}

func (x *QuerySubs_Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Pay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySubs_Subscription.ProtoReflect.Descriptor instead.
func (*QuerySubs_Subscription) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Pay_proto_rawDescGZIP(), []int{1, 0}
}

func (x *QuerySubs_Subscription) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

func (x *QuerySubs_Subscription) GetLeftMills() int64 {
	if x != nil && x.LeftMills != nil {
		return *x.LeftMills
	}
	return 0
}

type QuerySubs_Ret struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Code          *int32                    `protobuf:"varint,1,req,name=code" json:"code,omitempty"` // 查询结果. 0: 成功, 其它: 失败
	Subs          []*QuerySubs_Subscription `protobuf:"bytes,2,rep,name=subs" json:"subs,omitempty"`  // 订阅数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySubs_Ret) Reset() {
	*x = QuerySubs_Ret{}
	mi := &file_pkg_proto_Pay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySubs_Ret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySubs_Ret) ProtoMessage() {}

func (x *QuerySubs_Ret) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Pay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySubs_Ret.ProtoReflect.Descriptor instead.
func (*QuerySubs_Ret) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Pay_proto_rawDescGZIP(), []int{1, 1}
}

func (x *QuerySubs_Ret) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *QuerySubs_Ret) GetSubs() []*QuerySubs_Subscription {
	if x != nil {
		return x.Subs
	}
	return nil
}

var File_pkg_proto_Pay_proto protoreflect.FileDescriptor

const file_pkg_proto_Pay_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/Pay.proto\"\xa2\x02\n" +
	"\n" +
	"PayReceipt\x12\x18\n" +
	"\areceipt\x18\x01 \x02(\tR\areceipt\x12\x16\n" +
	"\x06gameId\x18\x02 \x02(\tR\x06gameId\x12\x1a\n" +
	"\bserverId\x18\x03 \x02(\tR\bserverId\x12\x1a\n" +
	"\bpassport\x18\x04 \x02(\tR\bpassport\x12\x1a\n" +
	"\bplayerId\x18\x05 \x02(\tR\bplayerId\x12\x1e\n" +
	"\n" +
	"playerName\x18\x06 \x02(\tR\n" +
	"playerName\x12\x18\n" +
	"\achannel\x18\a \x02(\tR\achannel\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12\x16\n" +
	"\x06locale\x18\t \x01(\tR\x06locale\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\x03R\n" +
	"createTime\"\xef\x01\n" +
	"\tQuerySubs\x12\x16\n" +
	"\x06gameId\x18\x01 \x02(\tR\x06gameId\x12\x1a\n" +
	"\bserverId\x18\x02 \x02(\tR\bserverId\x12\x1a\n" +
	"\bplayerId\x18\x03 \x02(\tR\bplayerId\x1aJ\n" +
	"\fSubscription\x12\x1c\n" +
	"\tproductId\x18\x01 \x02(\tR\tproductId\x12\x1c\n" +
	"\tleftMills\x18\x02 \x02(\x03R\tleftMills\x1aF\n" +
	"\x03Ret\x12\x12\n" +
	"\x04code\x18\x01 \x02(\x05R\x04code\x12+\n" +
	"\x04subs\x18\x02 \x03(\v2\x17.QuerySubs.SubscriptionR\x04subs\"O\n" +
	"\tApiResult\x12\x12\n" +
	"\x04code\x18\x01 \x02(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1c\n" +
	"\terrorCode\x18\x03 \x01(\x05R\terrorCodeB\"\n" +
	"\x17com.aly.codex.pay.protoZ\a./proto"

var (
	file_pkg_proto_Pay_proto_rawDescOnce sync.Once
	file_pkg_proto_Pay_proto_rawDescData []byte
)

func file_pkg_proto_Pay_proto_rawDescGZIP() []byte {
	file_pkg_proto_Pay_proto_rawDescOnce.Do(func() {
		file_pkg_proto_Pay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_Pay_proto_rawDesc), len(file_pkg_proto_Pay_proto_rawDesc)))
	})
	return file_pkg_proto_Pay_proto_rawDescData
}

var file_pkg_proto_Pay_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_Pay_proto_goTypes = []any{
	(*PayReceipt)(nil),             // 0: PayReceipt
	(*QuerySubs)(nil),              // 1: QuerySubs
	(*ApiResult)(nil),              // 2: ApiResult
	(*QuerySubs_Subscription)(nil), // 3: QuerySubs.Subscription
	(*QuerySubs_Ret)(nil),          // 4: QuerySubs.Ret
}
var file_pkg_proto_Pay_proto_depIdxs = []int32{
	3, // 0: QuerySubs.Ret.subs:type_name -> QuerySubs.Subscription
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_Pay_proto_init() }
func file_pkg_proto_Pay_proto_init() {
	if File_pkg_proto_Pay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_Pay_proto_rawDesc), len(file_pkg_proto_Pay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_Pay_proto_goTypes,
		DependencyIndexes: file_pkg_proto_Pay_proto_depIdxs,
		MessageInfos:      file_pkg_proto_Pay_proto_msgTypes,
	}.Build()
	File_pkg_proto_Pay_proto = out.File
	file_pkg_proto_Pay_proto_goTypes = nil
	file_pkg_proto_Pay_proto_depIdxs = nil
}
