// Code generated by hertz generator.

package pst

import (
	"context"
	"github.com/ywengineer/smart-kit/passport/internal"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	pst "github.com/ywengineer/smart-kit/passport/biz/model/mgr/pst"
)

// Detail .
// @router /mgr/passport/detail [GET]
func Detail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pst.MgrPassportDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, internal.ValidateErr(err))
		return
	}

	resp := new(pst.PassportData)

	c.JSON(consts.StatusOK, resp)
}
