// Code generated by hertz generator.

package simulate

import (
	"gitee.com/ywengineer/smart-kit/payment/internal/config"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _simulateMw() []app.HandlerFunc {
	return []app.HandlerFunc{config.CustomAuthorization()}
}
