// Code generated by hertz generator.

package simulate

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _simulateMw() []app.HandlerFunc {
	// your code...
	return nil
}
